modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="logixindustrialsolutions" #mandatory
version="0.1-dev" #mandatory
displayName="Logix Industrial Solutions" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="mod.png" #optional
#credits="" #optional
authors="Dr.LOGiQ" #optional
description='''
Description, coming soon!ᵗᵐ
'''
[[dependencies.logixindustrialsolutions]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.logixindustrialsolutions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"